//
//  StopViewerView.swift
//

import SwiftUI
import MapKit

struct DepartItem: Identifiable {
    let id = UUID()
    let patternId: String
    let transportNumber: String
    let toStation: String
    var departTimes: [DepartureItem]
    var isExpanded: Bool = false
    
    /// Get stop title.
    /// - Parameters:
    ///   - toStation: Parameter description
    /// - Returns: String
    func getStopTitle(toStation: String) -> String{
        var title = toStation
        let regex = "\\(([0-9a-zA-Z,:].*?)\\)"
        let removal = Helper.shared.regexMatches(for: regex, in: toStation)
        for r in removal{
            if let range = title.range(of: r){
                title.removeSubrange(range)
            }
        }
        
        if let fromTextRange = title.range(of: "from"){
            title.removeSubrange(fromTextRange.lowerBound..<title.endIndex)
        }
        
        if title.isEmpty {
            let routeId = self.routeId()
            let routes = RouteViewerModel.shared.pubRouteItems
            let filteredRoute = routes.first(where: {$0.route.id == routeId})
            if let filteredRoute = filteredRoute {
                title = filteredRoute.route.shortName ?? filteredRoute.route.longName ?? filteredRoute.route.busRouteNumber
            }
        }
        return title
    }
    
    /// Extract headsign from pattern.
    /// - Parameters:
    ///   - item: Parameter description
    /// - Returns: String
    func extractHeadsignFromPattern(item: DepartItem) -> String {
        var routeShortName = ""
        var headsign = ""
        
        let routeId = self.routeId()
        let routes = RouteViewerModel.shared.pubRouteItems
        var filteredRoute = routes.first(where: {$0.route.id == routeId})
        if filteredRoute == nil {
            filteredRoute = routes.first(where: {$0.route.id == routeIdV2()})
        }
        if let filteredRoute = filteredRoute {
            routeShortName = filteredRoute.route.shortName ?? filteredRoute.route.longName ?? filteredRoute.route.busRouteNumber
        }
        
        if headsign.isEmpty {
            if let departHeadSign = departTimes[0].item.headsign {
                headsign = departHeadSign
            }
        }
        
        // In case stop time headsign is blank, extract headsign from the pattern 'desc' attribute
        // (format: '49 to <Destination> (<destid>)[ from <Origin> (<originid)]').
        if headsign.isEmpty {
            let desc = toStation
            let matches = Helper.shared.extractSubstring(desc, regex: #"(?: to )(.*?)(?: \()"#)
            if let matches = matches {
                headsign = matches
            }
            
        }
        
        // If that regex didn't work, try the old regex
        if headsign.isEmpty {
            let desc = toStation
            let matches = Helper.shared.extractSubstring(desc, regex: #" to ([^(from)]+) \(.+\)"#)
            if let matches = matches {
                headsign = matches
            }
        }
        /*
           * In some cases the string generated by OTP doesn't include a " "
           * see https://github.com/opentripplanner/OpenTripPlanner/blob/7ce72cf554e6cf469d683869db5684eae3ce86f8/src/main/java/org/opentripplanner/graph_builder/module/TripPatternNamer.java#L72-L183
           * In this case, we need to rely on the routeShortName to determine what to remove
           */
        if headsign.isEmpty {
            let desc = toStation
            let matches = Helper.shared.extractSubstring(desc, regex: #"^[^(]*$"#)
            if let matches = matches {
                headsign = matches.replacingOccurrences(of: "\(routeShortName) ", with: "")
            }
        }

        
        // If the headsign is still blank, show the description
        if headsign.isEmpty{
            headsign = toStation
        }
        
        if headsign.isEmpty && toStation.isEmpty {
            if departTimes.count > 0 {
                if let departHeadSign = departTimes[0].item.headsign {
                    headsign = departHeadSign
                }
            }
        }
        
        if headsign.contains(routeShortName) {
            headsign = headsign.replacingOccurrences(of: routeShortName, with: "")
        }
        
        return "\(routeShortName) \(headsign)"
    }
    
    /// Route id v2
    /// - Returns: String
    /// Route id v 2.
    public func routeIdV2() -> String {
        let components = patternId.components(separatedBy: "::")
            guard let firstComponent = components.first else {
                return routeId()
            }
            return firstComponent
    }
    
    /// Route id
    /// - Returns: String
    /// Route id.
    public func routeId() -> String {
        let ids = patternId.split(separator: ":")
        var routeId = ""
        for i in 0..<ids.count - 2 {
            if routeId.count > 0 {
                routeId += ":"
            }
            routeId += ids[i]
        }
        return routeId
    }
}

struct GraphQLDepartItem: Identifiable {
    let id = UUID()
    let pattern: GraphQLPattern
    var departTimes: [GraphQLDepartureItem]
    var isExpanded: Bool = false
    
    /// Get stop title.
    /// - Parameters:
    ///   - toStation: Parameter description
    /// - Returns: String
    func getStopTitle(toStation: String) -> String{
        var title = toStation
        let regex = "\\(([0-9a-zA-Z,:].*?)\\)"
        let removal = Helper.shared.regexMatches(for: regex, in: toStation)
        for r in removal{
            if let range = title.range(of: r){
                title.removeSubrange(range)
            }
        }
        
        if let fromTextRange = title.range(of: "from"){
            title.removeSubrange(fromTextRange.lowerBound..<title.endIndex)
        }
        
        if title.isEmpty {
            let routeId = self.routeId()
            let routes = RouteViewerModel.shared.pubRouteItems
            let filteredRoute = routes.first(where: {$0.route.id == routeId})
            if let filteredRoute = filteredRoute {
                title = filteredRoute.route.shortName ?? filteredRoute.route.longName ?? filteredRoute.route.busRouteNumber
            }
        }
        return title
    }
    /// Route id v2
    /// - Returns: String
    /// Route id v 2.
    public func routeIdV2() -> String {
        let components = pattern.route.routeId.components(separatedBy: "::")
            guard let firstComponent = components.first else {
                return routeId()
            }
            return firstComponent
    }
    
    /// Route id
    /// - Returns: String
    /// Route id.
    public func routeId() -> String {
        let ids = pattern.route.routeId.split(separator: ":")
        var routeId = ""
        for i in 0..<ids.count - 2 {
            if routeId.count > 0 {
                routeId += ":"
            }
            routeId += ids[i]
        }
        return routeId
    }
}

struct StopViewerView: View {
    @Environment(\.sizeCategory) var sizeCategory
    @ObservedObject var stopViewer = StopViewerViewModel.shared
    @ObservedObject var mapManager = MapManager.shared
    @ObservedObject var loginFlowManager = LoginFlowManager.shared
    @ObservedObject var stopManager = StopsManager.shared
    @ObservedObject var tabBarMenuManager = TabBarMenuManager.shared
    @ObservedObject var session = AppSession.shared
    @ObservedObject var routeManager = RouteManager.shared
    @State private var isViewNextArrivals = true
    @State private var isDeparturesSelected = true
    @State private var isScheduleSelected = false
    @State private var isToggle : Bool = true
    @State private var timer: Timer?
    @State private var rotationAngle: Angle = .degrees(0)
    @State var wholeSize: CGSize = .zero
    @State var scrollViewSize: CGSize = .zero
    let spaceName = "scroll"
    let isLargeFontSize = AccessibilityManager.shared.pubIsLargeFontSize
    
    /// Body.
    /// - Parameters:
    ///   - some: Parameter description
    var body: some View {
        GeometryReader { geometry in
            ZStack {
                GeometryReader { geo in
                    mapManager.map()
                        .frame(height: (geo.size.height / 2 - (geometry.size.height * 0.05)), alignment: .center)
                        .accessibility(hidden:  true)
                        .edgesIgnoringSafeArea(.all).onAppear(){
                            mapManager.centerRoute()
                            mapManager.udateCompassPosition(newPosition: CGPoint(x: 15, y: (geometry.size.height * 0.2) + 15))
                        }
                }
                .zIndex(7)
                
                VStack{
                    HStack{
                        backButton
                            .frame(width: 48, height: 48, alignment: .center)
                            .background(Color.white)
                            .clipShape(Circle())
                            .shadow(radius: 5)
                            .padding(.top, ScreenSize.safeTop())
                            .padding()
                            .addAccessibility(text: AvailableAccessibilityItem.backButton.rawValue.localized())
                        Spacer()
                    }
                    Spacer()
                    stepInfoView
                        .background(Color.black)
                        .frame(height: geometry.size.height * 0.55)
                        .clipShape(RoundedCorner(radius: 10, corners: [.topLeft, .topRight]))
                }
                .zIndex(8)
                
            }
            .onChange(of: isToggle, perform: { newValue in
                if newValue {
                    rotationAngle += .degrees(360)
                    stopViewer.getGraphQLStopTimes()
                    startTimer()
                } else {
                    stopTimer()
                }
            })
            .onAppear(perform: {
                rotationAngle += .degrees(360)
                if let selectedStop = stopViewer.selectedStop {
                    let stop = selectedStop
                    let lat = stop.lat
                    let lon = stop.lon
                    let coordinates = CLLocationCoordinate2D(latitude: lat, longitude: lon)
                    mapManager.removeStopMarker()
                    mapManager.addStopMarker(coordinates: coordinates)
                    stopViewer.iconForAgencies()
                }
                
                DispatchQueue.main.asyncAfter(deadline: .now() + 0.2) {
                    mapManager.reCenterRouteBounds()
                }
                
                startTimer()
            })
            .onDisappear {
                stopTimer()
                if tabBarMenuManager.currentItemTab != .stops{
                    mapManager.removeStopMarker()
                }
                if mapManager.pubIsInTripPlan{
                    let viewArea = ViewArea(topRight: CGPoint(x:UIScreen.main.bounds.width,y:0), bottomLeft: CGPoint(x:0, y:Helper.shared.getDeafultViewHeight(heightPosition: .middle)))
                    mapManager.setCenterArea(viewArea: viewArea, mapViewHeight: Helper.shared.getDefaultMapViewHeight(), mapViewWidth: UIScreen.main.bounds.width)
                }
            }
            
        }
    }
    
    /// Start timer
    /// Starts timer.
    func startTimer() {
        timer = Timer.scheduledTimer(withTimeInterval: 10.0, repeats: true) { timer in
            // This closure will be called every 10 seconds
            rotationAngle += .degrees(360)
            stopViewer.getGraphQLStopTimes()
        }
    }
    
    /// Stop timer
    /// Stops timer.
    func stopTimer() {
        timer?.invalidate()
        timer = nil
    }
    
    
    /// Back button.
    /// - Parameters:
    ///   - some: Parameter description
    private var backButton: some View {
        Button(action: {
            stopViewer.pubScheduleSelectedDate = SearchManager.shared.dateSettings.departAt
            if mapManager.pubIsInTripPlanDetail {
                stopViewer.pubIsShowingStopViewer = false
                stopViewer.pubKeepShowingStopViewer = false
                return
            }
            
            let camera = mapManager.mapView.camera
            mapManager.pubMapCamera = camera
            mapManager.removeStopMarker()
            mapManager.renderRouteDirectionStopMarker(stops: routeManager.pubDirectionStops)
            stopViewer.pubIsShowingStopViewer = false
            stopViewer.pubKeepShowingStopViewer = false
            mapManager.forceCleanMapReDrawRoute()
            if (tabBarMenuManager.currentItemTab == .routes){
                if let geoData = routeManager.selectedDirectionGeoData{
                    routeManager.getDirectionStops(geometry: geoData)
                }
                if let route = routeManager.selectedRoute {
                    mapManager.removeRealTimeBusMarker()
                    routeManager.getRealtimeBusData(route: route, pattern: nil)
                }
            }
            if tabBarMenuManager.currentItemTab == .planTrip
                && tabBarMenuManager.currentViewTab == .planTrip
                && !(mapManager.pubHideAddressBar){
                DispatchQueue.main.asyncAfter(deadline: .now() + 1) {
                    if mapManager.pubIsInTripPlan{
                        let viewArea = ViewArea(topRight: CGPoint(x:UIScreen.main.bounds.width,y:Helper.shared.getDeafultViewHeight(heightPosition: .middle)), bottomLeft: CGPoint(x:0, y:Helper.shared.getDefaultMapViewHeight()))
                        mapManager.setCenterArea(viewArea: viewArea, mapViewHeight: Helper.shared.getDefaultMapViewHeight(), mapViewWidth: UIScreen.main.bounds.width,edgeInset: UIEdgeInsets(top: 20, left: 10, bottom: 0, right: 10))
                    }else if (SearchManager.shared.from != nil || SearchManager.shared.to != nil){
                        if SearchManager.shared.from != nil{
                            if let location = SearchManager.shared.from?.geometry?.coordinate{
                                mapManager.previewFromMarker(coordinates: location)
                            }
                        }
                        if SearchManager.shared.to != nil{
                            if let location = SearchManager.shared.to?.geometry?.coordinate{
                                mapManager.previewToMarker(coordinates: location)
                            }
                        }
                    }
                    else{
                        mapManager.mapView.setCamera(mapManager.pubMapCamera, animated: true)
                    }
                }
            }
            
            if tabBarMenuManager.currentItemTab == .routes
                && tabBarMenuManager.currentViewTab == .routes{
                if routeManager.selectedRoute == nil{
                    DispatchQueue.main.asyncAfter(deadline: .now() + 1) {
                        mapManager.mapView.setCamera(mapManager.pubMapCamera, animated: true)
                    }
                }
            }
            
            
        }) {
            Image("ic_leftarrow")
                .renderingMode(.template)
                .resizable()
                .padding(5)
                .foregroundColor(.black)
        }
        .frame(width: 25, height: 30)
    }
    
    /// Step info view.
    /// - Parameters:
    ///   - some: Parameter description
    private var stepInfoView: some View {
        ChildSizeReader(size: $wholeSize) {
            ScrollView{
                ChildSizeReader(size: $scrollViewSize) {
                    VStack(alignment: .leading, spacing: 15) {
                        
                        ViewerToolBar(text: stopViewer.selectedStop?.name ?? "", stop: stopViewer.selectedStop)
                            /// Initializes a new instance.
                            /// - Parameters:

                            ///   - maxHeight: .infinity

                            /// - Parameters:
                            .frame(maxHeight: .infinity)
                        
                        
                        if sizeCategory >= .accessibilityLarge{
                            Spacer()
                        }
                        
                        VStack{
                            planTripView
                        }.fixedSize(horizontal: false, vertical: true)
                        
                        if isDeparturesSelected{
                            if isLargeFontSize {
                                autoRefreshViewAODA.padding(.horizontal, 16)
                            } else {
                                autoRefreshView.padding(.horizontal, 16)
                            }
                        }
                        // MARK: - removed timezone label
//                        infoView
                        if isScheduleSelected{
                            HStack{
                                Spacer()
                                calendarView.padding(.trailing, 15)
                            }
                        }
                        if isViewNextArrivals {
                            if stopViewer.isLoading{
                                processingView
                            }else{
                                infoListView
                            }
                        } else {
                            if stopViewer.isLoading{
                                processingView
                            }else{
                                scheduleView
                                
                            }
                        }
                        Spacer()
                    }
                    .background(
                        GeometryReader { proxy in
                            Color.clear.preference(
                                key: ViewOffsetKey.self,
                                value: -1 * proxy.frame(in: .named(spaceName)).origin.y
                            )
                        }
                    )
                    .onPreferenceChange(
                        ViewOffsetKey.self,
                        perform: { value in
                            if value >= scrollViewSize.height - wholeSize.height {
                                if !stopViewer.isSchedulesLoading {
                                    stopViewer.loadNextDataChunk()
                                }
                            }
                        }
                    )
                }
            }.background(Color.white)
                .coordinateSpace(name: spaceName)
        }
        .onChange(
            of: scrollViewSize,
            perform: { value in
            }
        )
        .onAppear(perform: {
            stopViewer.pubAgencyIcons.removeAll()
        })

    }
    
    /// Processing view.
    /// - Parameters:
    ///   - some: Parameter description
    private var processingView: some View {
        VStack{
            HStack{
                Spacer()
                ProgressView().foregroundColor(Color.black).frame(width: 20, height: 20)
                Spacer()
            }
        }
    }
    
    
    /// Schedule view.
    /// - Parameters:
    ///   - some: Parameter description
    private var scheduleView: some View {
        VStack{
            if AccessibilityManager.shared.pubIsLargeFontSize {
                topViewAODA
            } else {
                topView
            }
            VStack {
                ForEach(0..<stopViewer.scheduleTimes.count, id: \.self) { index in
                    StopScheduleItemView(item: stopViewer.scheduleTimes[index], index: index).id(index).background(index == stopViewer.scrollToIndex ? Color.yellow : Color.white)
                }
                if stopViewer.isSchedulesLoading {
                    ProgressView("Loading...".localized())
                        .padding()
                }
            }
               
        }.padding(.horizontal, 16)
            .background(Color.white)
        
    }
    
    /// Top view.
    /// - Parameters:
    ///   - some: Parameter description
    var topView: some View {
        HStack{
            TextLabel("Route".localized()).font(.title3).frame(alignment: .leading).foregroundColor(Color.black).padding(.trailing, 10)
            TextLabel("Destination".localized()).font(.title3).foregroundColor(Color.black)
            Spacer()
            TextLabel("Departure".localized()).font(.title3).frame(alignment: .trailing).foregroundColor(Color.black)
        }
    }
    
    /// Top view a o d a.
    /// - Parameters:
    ///   - some: Parameter description
    var topViewAODA: some View {
        HStack{
            VStack(alignment: .leading){
                TextLabel("Route".localized(), .bold, .title3).frame(alignment: .leading).foregroundColor(Color.black).padding(.trailing, 10)
                TextLabel("Destination".localized(),.bold, .title3).foregroundColor(Color.black)
                TextLabel("Departure".localized(),.bold, .title3).frame(alignment: .trailing).foregroundColor(Color.black)
            }
            Spacer()
        }
    }
    
    /// Convert time.
    /// - Parameters:
    ///   - time: Parameter description
    /// - Returns: Date
    func convertTime(time: String) -> Date{
        let inFormatter = DateFormatter()
        let language = SettingsManager.shared.appLanguage
        inFormatter.locale = Locale(identifier: language.languageCode())
        inFormatter.dateFormat = "hh:mm a"
        inFormatter.timeZone = EnvironmentManager.shared.currentTimezone
        let convertedTime = inFormatter.date(from: time) ?? Date()
        return convertedTime
    }
    
    
    /// Auto refresh view.
    /// - Parameters:
    ///   - some: Parameter description
    private var autoRefreshView: some View {
        HStack {
            autorefreshTimeButton
            Spacer()
            autorefreshButton
        }
    }
    
    /// Auto refresh view a o d a.
    /// - Parameters:
    ///   - some: Parameter description
    private var autoRefreshViewAODA: some View {
        VStack(spacing: 5) {
            HStack {
                autorefreshTimeButton
                Spacer()
            }
            autorefreshButton
        }
    }
    
    /// Autorefresh button.
    /// - Parameters:
    ///   - some: Parameter description
    private var autorefreshButton: some View {
        HStack(spacing: 20){
            TextLabel("Auto Refresh".localized())
                .font(.body)
                .foregroundColor(.gray)
            Toggle("", isOn: $isToggle).labelsHidden().toggleStyle(SwitchToggleStyle(tint: Color.main))
        }
    }
    
    /// Calendar view.
    /// - Parameters:
    ///   - some: Parameter description
    private var calendarView: some View {
        HStack(alignment: .center) {
            CalendarView(date: stopViewer.pubScheduleSelectedDate ?? Date(), components: .date,
                         dateSelected: { date in
                stopViewer.pubScheduleSelectedDate = date
            })
            .font(.body)
            .foregroundColor(Color.blue)
            .accentColor(Color.blue)
            Image("calendar_search_icon")
                .resizable()
                .frame(width: 20, height: 20)
        }
    }
    
    /// Autorefresh time button.
    /// - Parameters:
    ///   - some: Parameter description
    private var autorefreshTimeButton: some View {
        Button(action: {
            rotationAngle += .degrees(360)
            stopViewer.getGraphQLStopTimes()
        }) {
            HStack {
                Image("refresh_icon")
                    .resizable()
                    .frame(width: isLargeFontSize ? 30 : 20, height: isLargeFontSize ? 30 : 20)
                    .rotationEffect(rotationAngle)
                    .animation(.linear(duration: 1.0), value: rotationAngle)
                TextLabel(stopViewer.getLastStopRefreshTime())
                    .font(.headline)
                    .foregroundColor(.gray)
            }
        }
    }
    
    /// Plan trip view.
    /// - Parameters:
    ///   - some: Parameter description
    private var planTripView: some View {
        var latitude:Double = 0
        var longitude:Double = 0
        var title = ""
        if let selectedStop = stopViewer.selectedStop {
            let stop = selectedStop
            latitude = stop.lat
            longitude = stop.lon
            title = stop.name
        }
        return VStack{
            if isLargeFontSize {
                VStack(alignment: .leading){
                    StopIDPlanView(fromAction: {
                        mapManager.fromToDestionation(isFrom: true, latitude: latitude, longitude: longitude, title: title) {
                            mapManager.cleanPlotRoute()
                            mapManager.deSelectAnnotations()
                            stopViewer.pubIsShowingStopViewer = false
                            stopViewer.pubKeepShowingStopViewer = false
                            TripViewerViewModel.shared.pubIsShowingTripViewer = false
                            let location = Coordinate(latitude: latitude, longitude: longitude)
                            tabBarMenuManager.currentItemTab = .planTrip
                            mapManager.previewFromMarker(coordinates: location)
                            mapManager.pubShowUsersCurrentLocation = false
                            tabBarMenuManager.currentViewTab = .planTrip
                            tabBarMenuManager.seletedTab = TabBarItem(type: .planTrip)
                            if SearchManager.shared.to != nil{
                                if let location = SearchManager.shared.to?.geometry?.coordinate{
                                    mapManager.previewToMarker(coordinates: location)
                                }
                            }
                        }
                    }, toAction: {
                        mapManager.fromToDestionation(isFrom: false, latitude: latitude, longitude: longitude, title: title) {
                            mapManager.cleanPlotRoute()
                            mapManager.deSelectAnnotations()
                            stopViewer.pubIsShowingStopViewer = false
                            stopViewer.pubKeepShowingStopViewer = false
                            TripViewerViewModel.shared.pubIsShowingTripViewer = false
                            let location = Coordinate(latitude: latitude, longitude: longitude)
                            tabBarMenuManager.currentItemTab = .planTrip
                            mapManager.previewToMarker(coordinates: location)
                            tabBarMenuManager.currentViewTab = .planTrip
                            tabBarMenuManager.seletedTab = TabBarItem(type: .planTrip)
                            if SearchManager.shared.from != nil{
                                if let location = SearchManager.shared.from?.geometry?.coordinate{
                                    mapManager.previewFromMarker(coordinates: location)
                                }
                            }
                        }
                    })
                    Spacer()
                    tripPlanTimeViewAODA
                }
            } else {
                HStack(alignment: .center){
                    StopIDPlanView(fromAction: {
                        mapManager.fromToDestionation(isFrom: true, latitude: latitude, longitude: longitude, title: title) {
                            mapManager.cleanPlotRoute()
                            mapManager.deSelectAnnotations()
                            stopViewer.pubIsShowingStopViewer = false
                            stopViewer.pubKeepShowingStopViewer = false
                            TripViewerViewModel.shared.pubIsShowingTripViewer = false
                            let location = Coordinate(latitude: latitude, longitude: longitude)
                            tabBarMenuManager.currentItemTab = .planTrip
                            mapManager.previewFromMarker(coordinates: location)
                            mapManager.pubShowUsersCurrentLocation = false
                            
                            TripPlanningManager.shared.isItineraryResult = true
                            TripPlanningManager.shared.pubShowFullPage = true
                            tabBarMenuManager.currentViewTab = .planTrip
                            if SearchManager.shared.to != nil{
                                if let location = SearchManager.shared.to?.geometry?.coordinate{
                                    mapManager.previewToMarker(coordinates: location)
                                }
                            }
                        }
                    }, toAction: {
                        mapManager.fromToDestionation(isFrom: false, latitude: latitude, longitude: longitude, title: title) {
                            mapManager.cleanPlotRoute()
                            mapManager.deSelectAnnotations()
                            stopViewer.pubIsShowingStopViewer = false
                            stopViewer.pubKeepShowingStopViewer = false
                            TripViewerViewModel.shared.pubIsShowingTripViewer = false
                            
                            let location = Coordinate(latitude: latitude, longitude: longitude)
                            
                            tabBarMenuManager.currentItemTab = .planTrip
                            mapManager.previewToMarker(coordinates: location)
                            TripPlanningManager.shared.isItineraryResult = true
                            TripPlanningManager.shared.pubShowFullPage = true
                            tabBarMenuManager.currentViewTab = .planTrip
                            if SearchManager.shared.from != nil{
                                if let location = SearchManager.shared.from?.geometry?.coordinate{
                                    mapManager.previewFromMarker(coordinates: location)
                                }
                            }
                        }
                    })
                    Spacer()
                    tripPlanTimeView
                }
                .frame(maxWidth: ScreenSize.width() - 32)
            }
        }
        .frame(maxWidth: ScreenSize.width() - 32)
        .padding(.horizontal, 16)
        .padding(.vertical, 10)
    }
    
    /// Trip plan time view.
    /// - Parameters:
    ///   - some: Parameter description
    private var tripPlanTimeView: some View {
        VStack {
            HStack(spacing: 3) {
                departureButtonView.padding(.leading, 3)
                scheduleButtonView.padding(.trailing, 3)
            }.padding([.top, .bottom],2)
        }
        .frame(width: 220, height: 34)
        .background(Color.gray_main)
        .cornerRadius(5)
    }
    
    /// Trip plan time view a o d a.
    /// - Parameters:
    ///   - some: Parameter description
    private var tripPlanTimeViewAODA: some View {
        VStack {
            VStack(spacing: 3) {
                departureButtonView.padding(.leading, 3)
                scheduleButtonView.padding(.trailing, 3)
            }.padding([.top, .bottom],2)
        }
        .background(Color.gray_main)
        .cornerRadius(5)
    }
    
    /// Departure button view.
    /// - Parameters:
    ///   - some: Parameter description
    private var departureButtonView: some View {
        ZStack {
            if isLargeFontSize {
                if isDeparturesSelected {
                    departureButtonAODA
                        .background(Color.white)
                        .cornerRadius(5)
                        .shadow(radius: 5)
                        .padding(.horizontal, 2)
                } else {
                    departureButtonAODA
                }
            } else {
                if isDeparturesSelected {
                    departureButton
                        .background(Color.white)
                        .cornerRadius(5)
                        .shadow(radius: 5)
                } else {
                    departureButton
                }
            }
        }
    }
    
    /// Departure button.
    /// - Parameters:
    ///   - some: Parameter description
    private var departureButton: some View {
        Button(action: {
            stopViewer.pubDate = SearchManager.shared.dateSettings.departAt
            isDeparturesSelected.toggle()
            isScheduleSelected.toggle()
            isViewNextArrivals.toggle()
        }) {
            HStack {
                Spacer()
                TextLabel("Departures".localized(), .bold, .footnote)
                    .foregroundColor(.black)
                Spacer()
            }
        }
        .padding(.horizontal, 5)
        .frame(width: 110, height: 30)
    }
    
    /// Departure button a o d a.
    /// - Parameters:
    ///   - some: Parameter description
    private var departureButtonAODA: some View {
        Button(action: {
            stopViewer.pubDate = SearchManager.shared.dateSettings.departAt
            isDeparturesSelected.toggle()
            isScheduleSelected.toggle()
            isViewNextArrivals.toggle()
        }) {
            HStack {
                Spacer()
                TextLabel("Departures".localized(), .bold, .footnote)
                    .foregroundColor(.black)
                    .fixedSize(horizontal: false, vertical: true)
                Spacer()
            }
        }
        .padding(10)
    }
    
    /// Schedule button view.
    /// - Parameters:
    ///   - some: Parameter description
    private var scheduleButtonView: some View {
        ZStack {
            if isLargeFontSize {
                if isScheduleSelected {
                    scheduleButtonAODA
                        .background(Color.white)
                        .cornerRadius(5)
                        .shadow(radius: 5)
                        .padding(.horizontal, 2)
                } else {
                    scheduleButtonAODA
                }
            } else {
                if isScheduleSelected {
                    scheduleButton
                        .background(Color.white)
                        .cornerRadius(5)
                        .shadow(radius: 5)
                } else {
                    scheduleButton
                }
            }
        }
    }
    
    /// Schedule button.
    /// - Parameters:
    ///   - some: Parameter description
    private var scheduleButton: some View {
        Button(action: {
            
            isScheduleSelected.toggle()
            isDeparturesSelected.toggle()
            isViewNextArrivals.toggle()
            if !isViewNextArrivals {
                stopViewer.getGraphQLStopSchedules()
            }
        }) {
            HStack {
                Spacer()
                TextLabel("Schedule".localized(), .bold, .footnote)
                    .foregroundColor(.black)
                Spacer()
            }
        }
        .padding(.horizontal, 5)
        .frame(width: 100, height: 30)
    }
    
    /// Schedule button a o d a.
    /// - Parameters:
    ///   - some: Parameter description
    private var scheduleButtonAODA: some View {
        Button(action: {
            isScheduleSelected.toggle()
            isDeparturesSelected.toggle()
            isViewNextArrivals.toggle()
            if !isViewNextArrivals {
                stopViewer.getGraphQLStopSchedules()
            }
        }) {
            HStack {
                Spacer()
                TextLabel("Schedule".localized(), .bold, .footnote)
                    .foregroundColor(.black)
                    .fixedSize(horizontal: false, vertical: true)
                Spacer()
            }
        }
        .padding(10)
    }
    
    /// Info view.
    /// - Parameters:
    ///   - some: Parameter description
    private var infoView: some View {
        VStack(alignment: .center) {
            HStack(spacing: 0){
                Spacer()
                Image(systemName: "info.circle.fill")
                    .foregroundColor(Color.black)
                TextLabel("Departure times are shown in".localized())
                    .font(.footnote)
                    .foregroundColor(.black)
                    .padding(.trailing, 3)
                TextLabel(BrandConfig.shared.timezone == "America/Vancouver" ? "PDT" : BrandConfig.shared.timezone, .bold, .footnote)
                    .foregroundColor(.black)
                Spacer()
            }
            .padding(15)
            .background(Color.second)
            .padding(.horizontal, 10)
        }
    }
    
    /// Info list view.
    /// - Parameters:
    ///   - some: Parameter description
    private var infoListView: some View {
        VStack {
            if stopViewer.graphQLDepartItems.isEmpty {
                HStack {
                    Spacer()
                    Text("No stop times found for date.".localized())
                    Spacer()
                }
            } else {
                ForEach(0..<stopViewer.graphQLDepartItems.count, id:\.self) { index in
                    DepartItemView(item: $stopViewer.graphQLDepartItems[index])
                }
            }
        }
    }
    
    /// Stop time item.
    /// - Parameters:
    ///   - model: Parameter description
    /// - Returns: DepartItem
    private func stopTimeItem(model: StopViewerModel) -> DepartItem {
        return  DepartItem(patternId:model.pattern.id ?? "", transportNumber: "", toStation: model.pattern.desc ?? "", departTimes: model.items)
    }
    
    /// Map layer options.
    /// - Parameters:
    ///   - some: Parameter description
    private var mapLayerOptions: some View {
        MapSettingsView()
    }
}

extension StopViewerModel {
    /// Depart item.
    /// - Parameters:
    ///   - DepartItem: Parameter description
    var departItem: DepartItem {
        return DepartItem(patternId:self.pattern.id ?? "", transportNumber: "", toStation: pattern.desc ?? "", departTimes: items)
    }
    /// Items.
    /// - Parameters:
    ///   - [DepartureItem]: Parameter description
    var items: [DepartureItem] {
        return times.map({ DepartureItem(time: $0.departureDate.timeIntervalSince1970, item: $0) })
    }
    
    /// Route.
    /// - Parameters:
    ///   - String: Parameter description
    var route: String {
        let desc = pattern.desc ?? ""
        return desc.components(separatedBy: " ").first ?? ""
    }
    
    /// To string.
    /// - Parameters:
    ///   - String: Parameter description
    var toString: String {
        let desc = pattern.desc ?? ""
        return desc.slice(from: "to", to: "(") ?? ""
    }
    
    
    /// Schedule.
    /// - Parameters:
    ///   - [StopScheduleModel]: Parameter description
    var schedule: [StopScheduleModel] {
        return times.map({
            return StopScheduleModel(time: $0, route: route, to: $0.headsign ?? toString)
        })
    }
    
    /// Schedule items.
    /// - Parameters:
    ///   - [StopScheduleItem]: Parameter description
    var scheduleItems: [StopScheduleItem] {
        return times.map({
            let time = $0.departureDate.timeForStopViewer()
            return StopScheduleItem(leftText: route, middleText: toString, rightText: time)
        })
    }
    
    /// Schedule item.
    /// - Parameters:
    ///   - StopScheduleItem: Parameter description
    var scheduleItem: StopScheduleItem {
        return StopScheduleItem(leftText: "", middleText: "", rightText: "")
    }
    
    /// Top schedule item.
    /// - Parameters:
    ///   - StopScheduleItem: Parameter description
    static var topScheduleItem: StopScheduleItem {
        return StopScheduleItem(leftText: "Route".localized(), middleText: "To".localized(), rightText: "Departure".localized())
    }
}

extension GraphQLStopViewerModel {
    /// Depart item.
    /// - Parameters:
    ///   - GraphQLDepartItem: Parameter description
    var departItem: GraphQLDepartItem {
        return GraphQLDepartItem(pattern: pattern, departTimes: items)
    }
    /// Items.
    /// - Parameters:
    ///   - [GraphQLDepartureItem]: Parameter description
    var items: [GraphQLDepartureItem] {
        return times.map({ GraphQLDepartureItem(time: $0.departureDate.timeIntervalSince1970, item: $0) })
    }
    
    /// Route.
    /// - Parameters:
    ///   - String: Parameter description
    var route: String {
        let desc = pattern.desc ?? ""
        return desc.components(separatedBy: " ").first ?? ""
    }
    
    /// To string.
    /// - Parameters:
    ///   - String: Parameter description
    var toString: String {
        let desc = pattern.desc ?? ""
        return desc.slice(from: "to", to: "(") ?? ""
    }
    
    
    /// Schedule.
    /// - Parameters:
    ///   - [GraphQLStopScheduleModel]: Parameter description
    var schedule: [GraphQLStopScheduleModel] {
        return times.map({
            return GraphQLStopScheduleModel(time: $0, route: route, to: $0.headsign ?? toString)
        })
    }
    
    /// Schedule items.
    /// - Parameters:
    ///   - [StopScheduleItem]: Parameter description
    var scheduleItems: [StopScheduleItem] {
        return times.map({
            let time = $0.departureDate.timeForStopViewer()
            return StopScheduleItem(leftText: route, middleText: toString, rightText: time)
        })
    }
    
    /// Schedule item.
    /// - Parameters:
    ///   - StopScheduleItem: Parameter description
    var scheduleItem: StopScheduleItem {
        return StopScheduleItem(leftText: "", middleText: "", rightText: "")
    }
    
    /// Top schedule item.
    /// - Parameters:
    ///   - StopScheduleItem: Parameter description
    static var topScheduleItem: StopScheduleItem {
        return StopScheduleItem(leftText: "Route".localized(), middleText: "To".localized(), rightText: "Departure".localized())
    }
}

struct StepItem: Identifiable {
    let id = UUID().uuidString
    let step: Step
}

struct TripInfoItem: Identifiable {
    let id = UUID().uuidString
    let stop: Stop
    let stopTime: StopTime?
}

struct DepartItemView: View {
    @ObservedObject var stopViewerViewModel = StopViewerViewModel.shared
    @ObservedObject var mapManager = MapManager.shared
    @State var routeManager = RouteManager.shared
    @Binding var item: GraphQLDepartItem
    
    /// Body.
    /// - Parameters:
    ///   - some: Parameter description
    var body: some View {
        return VStack {
            if AccessibilityManager.shared.pubIsLargeFontSize {
                topViewAODA(isSelected: item.isExpanded)
            } else {
                topView(isSelected: item.isExpanded)
            }
            Divider()
                .background(Color.black)
            if item.isExpanded {
                departuresView
            }
        }
        .background(Color.white)
        .padding(15)
    }
    
    /// Icon for agency
    /// - Returns: UIImage?
    /// Icon for agency.
    func iconForAgency() -> UIImage?{
        let agencyName = item.pattern.route.agency.name
        let mappedAgency = Helper.shared.mapAgencyNameAliase(agencyName: agencyName)
        var agencyImage: UIImage? = nil
        agencyImage = RouteViewerModel.shared.agencyLogos[mappedAgency.lowercased()]
        return agencyImage
    }
    
    func deparureTopButtonAction() {
        item.isExpanded.toggle()
        if item.isExpanded {
            let routeId = item.routeId()
            stopViewerViewModel.pubSelectedDepartItem = item
            routeManager.presentBusRoute(id: routeId)
        }else{
            stopViewerViewModel.pubSelectedDepartItem = nil
            mapManager.forceCleanMapReDrawRoute()
            DispatchQueue.main.asyncAfter(deadline: .now() + 0.5) {
                mapManager.reCenterRouteBounds()
            }
        }
        if let selectedStop = StopViewerViewModel.shared.selectedStop{
            let stop = selectedStop
            let lat = stop.lat
            let lon = stop.lon
            let coordinates = CLLocationCoordinate2D(latitude: lat, longitude: lon)
            mapManager.removeStopMarker()
            mapManager.addStopMarker(coordinates: coordinates)
        }
    }
    
    /// Top view.
    /// - Parameters:
    ///   - isSelected: Parameter description
    /// - Returns: some View
    func topView(isSelected: Bool) -> some View {
        let agencyImage = iconForAgency()
        return HStack {
                if let agencyImage = agencyImage {
                    Image(uiImage: agencyImage)
                        .resizable().aspectRatio(contentMode: .fit)
                        .frame(width: 50, height: 50, alignment: .center)
                        .padding(.bottom, 5)
                }
            
            TextLabel(stopViewerViewModel.graphQLExtractHeadsignFromPattern(item: item))
                .font(isSelected ? .body.bold() : .body)
                .foregroundColor(.black)
                .padding(.leading, 5)
            
            Spacer()
            if let departTime = item.departTimes.first {
                graphQLTimeView(departTime: departTime, isSelected: item.isExpanded, isFormatted: true)
                    .frame(width: 80, alignment: .top)
            }
            Button(action: {
                deparureTopButtonAction()
            }) {
                Image(item.isExpanded ? "expand_up_icon" : "expand_down_icon")
                    .resizable()
                    .frame(width: 25, height: 25)
            }
            .frame(width: 40, alignment: .center)
            .accessibilityElement(children: .ignore)
            .addAccessibility(text: item.isExpanded ? AvailableAccessibilityItem.departureCollapsButton.rawValue : AvailableAccessibilityItem.departureExpandButton.rawValue)
            .accessibilityAction {
                deparureTopButtonAction()
            }
            .accessibilityRemoveTraits(.isButton)

        }.padding(.top, 10)
    }
    
    /// Top view a o d a.
    /// - Parameters:
    ///   - isSelected: Parameter description
    /// - Returns: some View
    func topViewAODA(isSelected: Bool) -> some View {
        let agencyImage = iconForAgency()
        return VStack {
                if let agencyImage = agencyImage {
                    HStack {
                        Image(uiImage: agencyImage)
                            .resizable().aspectRatio(contentMode: .fit)
                            .frame(width: AccessibilityManager.shared.getFontSize(), height: AccessibilityManager.shared.getFontSize(), alignment: .center)
                            .padding(.bottom, 5)
                        Spacer()
                    }
                }
            HStack {
                TextLabel(stopViewerViewModel.graphQLExtractHeadsignFromPattern(item: item))
                    .font(isSelected ? .body.bold() : .body)
                    .foregroundColor(.black)
                Spacer()
            }
            if let departTime = item.departTimes.first {
                HStack {
                    graphQLTimeViewAODA(departTime: departTime, isSelected: item.isExpanded, isFormatted: true)
                    Spacer()
                    Button(action: {
                        deparureTopButtonAction()
                    }) {
                        Image(item.isExpanded ? "expand_up_icon" : "expand_down_icon")
                            .resizable()
                            .frame(width: 35, height: 35)
                    }
                    .frame(width: 40, alignment: .center)
                    .accessibilityElement(children: .ignore)
                    .addAccessibility(text: item.isExpanded ? AvailableAccessibilityItem.departureCollapsButton.rawValue : AvailableAccessibilityItem.departureExpandButton.rawValue)
                    .accessibilityAction {
                        deparureTopButtonAction()
                    }
                    .accessibilityRemoveTraits(.isButton)
                }
            }
        }.padding(.top, 10)
    }
    
    /// Time view.
    /// - Parameters:
    ///   - departTime: Parameter description
    ///   - isSelected: Parameter description
    /// - Returns: some View
    private func timeView(departTime: DepartureItem, isSelected: Bool) -> some View {
        TextLabel(departTime.item.departureSinceNow.localized(), isSelected ? .bold : .regular,  departTime.item.departureSinceNow.localized().count > 7 ? .subheadline : .body)
            .foregroundColor(.gray)
            .lineLimit(nil)
            .fixedSize(horizontal: false, vertical: true)
            .frame(maxWidth: 120, alignment: .leading)
    }
    
    /// Graph q l time view.
    /// - Parameters:
    ///   - departTime: Parameter description
    ///   - isSelected: Parameter description
    ///   - isFormatted: Parameter description
    /// - Returns: some View
    private func graphQLTimeView(departTime: GraphQLDepartureItem, isSelected: Bool, isFormatted: Bool) -> some View {
        TextLabel(departTime.item.departureSinceNow(isFormatted: isFormatted).localized(), isSelected ? .bold : .regular,  departTime.item.departureSinceNow(isFormatted: isFormatted).localized().count > 7 ? .subheadline : .body)
            .foregroundColor(.gray)
            .lineLimit(nil)
            .fixedSize(horizontal: false, vertical: true)
            .frame(maxWidth: 120, alignment: .leading)
    }
    
    /// Time view a o d a.
    /// - Parameters:
    ///   - departTime: Parameter description
    ///   - isSelected: Parameter description
    /// - Returns: some View
    private func timeViewAODA(departTime: DepartureItem, isSelected: Bool) -> some View {
        HStack {
            TextLabel(departTime.item.departureSinceNow.localized(), isSelected ? .bold : .regular)
                .foregroundColor(.gray)
                .fixedSize(horizontal: false, vertical: true)
            Spacer()
        }
    }
    
    /// Graph q l time view a o d a.
    /// - Parameters:
    ///   - departTime: Parameter description
    ///   - isSelected: Parameter description
    ///   - isFormatted: Parameter description
    /// - Returns: some View
    private func graphQLTimeViewAODA(departTime: GraphQLDepartureItem, isSelected: Bool, isFormatted: Bool) -> some View {
        HStack {
            TextLabel(departTime.item.departureSinceNow(isFormatted: isFormatted).localized(), isSelected ? .bold : .regular)
                .foregroundColor(.gray)
                .fixedSize(horizontal: false, vertical: true)
            Spacer()
        }
    }
    
    /// Departures view.
    /// - Parameters:
    ///   - some: Parameter description
    private var departuresView: some View {
        ScrollView{
            VStack(alignment: .trailing) {
                ForEach(item.departTimes) { departureItem in
                    if AccessibilityManager.shared.pubIsLargeFontSize {
                        graphQLDeparturesItemAODA(departureItem: departureItem)
                            .padding(.bottom, 10)
                    } else {
                        graphQLDeparturesItem(departureItem: departureItem)
                    }
                }
            }
            .padding(.bottom, 10)
        }
    }
    
    /// Departures item.
    /// - Parameters:
    ///   - departureItem: Parameter description
    /// - Returns: some View
    func departuresItem(departureItem: DepartureItem) -> some View {
        return HStack {
            Image("ic_clock").resizable()
                .frame(width: 25, height: 25, alignment: .center)
            timeView(departTime: departureItem, isSelected: false)
                .frame(width: 80, alignment: .leading)
            Spacer()
            TextLabel(departureItem.item.departureDate.timeForStopViewer(), .bold, .body)
                .foregroundColor(.gray)
            Spacer()
            HStack{
                TextLabel(getMappedState(state: departureItem.item.realtimeState).localized())
                    .font(.footnote)
                    .foregroundColor(.white)
                    .padding(10)
            }
            .background(Color.main)
            .cornerRadius(5)
            .frame(width: 120)
        }
    }
    
    /// Departures item a o d a.
    /// - Parameters:
    ///   - departureItem: Parameter description
    /// - Returns: some View
    func departuresItemAODA(departureItem: DepartureItem) -> some View {
        return HStack(){
            Image("ic_clock").resizable()
                .frame(width: AccessibilityManager.shared.getFontSize(), height: AccessibilityManager.shared.getFontSize(), alignment: .center)
            VStack(alignment: .leading, spacing: 0){
                timeViewAODA(departTime: departureItem, isSelected: false)
                HStack {
                    TextLabel(departureItem.item.departureDate.timeForStopViewer(), .bold, .body)
                        .foregroundColor(.gray)
                    Spacer()
                }
                HStack{
                    HStack{
                        TextLabel(getMappedState(state: departureItem.item.realtimeState).localized())
                            .font(.footnote)
                            .foregroundColor(.white)
                            .padding(10)
                    }
                    .background(Color.main)
                    .cornerRadius(5)
                    Spacer()
                }
            }
        }
    }
    
    /// Graph q l departures item.
    /// - Parameters:
    ///   - departureItem: Parameter description
    /// - Returns: some View
    func graphQLDeparturesItem(departureItem: GraphQLDepartureItem) -> some View {
        return HStack {
            Image("ic_clock").resizable()
                .frame(width: 25, height: 25, alignment: .center)
            graphQLTimeView(departTime: departureItem, isSelected: false, isFormatted: false)
                .frame(width: 80, alignment: .leading)
            Spacer()
            TextLabel(departureItem.item.departureDate.timeForStopViewer(), .bold, .body)
                .foregroundColor(.gray)
            Spacer()
            HStack{
                TextLabel(getMappedState(state: departureItem.item.realtimeState).localized())
                    .font(.footnote)
                    .foregroundColor(.white)
                    .padding(10)
            }
            .background(Color.main)
            .cornerRadius(5)
            .frame(width: 120)
        }
    }
    
    /// Graph q l departures item a o d a.
    /// - Parameters:
    ///   - departureItem: Parameter description
    /// - Returns: some View
    func graphQLDeparturesItemAODA(departureItem: GraphQLDepartureItem) -> some View {
        return HStack(){
            Image("ic_clock").resizable()
                .frame(width: AccessibilityManager.shared.getFontSize(), height: AccessibilityManager.shared.getFontSize(), alignment: .center)
            VStack(alignment: .leading, spacing: 0){
                graphQLTimeView(departTime: departureItem, isSelected: false, isFormatted: false)
                HStack {
                    TextLabel(departureItem.item.departureDate.timeForStopViewer(), .bold, .body)
                        .foregroundColor(.gray)
                    Spacer()
                }
                HStack{
                    HStack{
                        TextLabel(getMappedState(state: departureItem.item.realtimeState).localized())
                            .font(.footnote)
                            .foregroundColor(.white)
                            .padding(10)
                    }
                    .background(Color.main)
                    .cornerRadius(5)
                    Spacer()
                }
            }
        }
    }
    
    /// Get mapped state.
    /// - Parameters:
    ///   - state: Parameter description
    /// - Returns: String
    func getMappedState(state: String) -> String{
        if state == "UPDATED" {
            return "REAL-TIME"
        } else {
            return state
        }
    }
    
}

struct DepartureItem: Identifiable {
    let id = UUID()
    let time: TimeInterval
    let item: StopTime
}

struct GraphQLDepartureItem: Identifiable {
    let id = UUID()
    let time: TimeInterval
    let item: GraphQLStopTime
}

struct StopViewr_Previews: PreviewProvider {
    /// Previews.
    /// - Parameters:
    ///   - some: Parameter description
    static var previews: some View {
        StopViewerView()
        
    }
}
